---
- name: Configure the server and install localhost
  hosts: localhost
  gather_facts: false
  tags: algo
  become: true
  vars_files:
    - config.cfg

  roles:
    - role: common
      tags: common
    - role: dns_encryption
      when: dns_encryption
      tags: dns_encryption
